# Generated by Django 4.1 on 2022-08-17 21:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 45, 39, 707096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires_phone',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 21, 48, 39, 707096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
